# Blackjack Rules
decks: 6
minimum_bet: 10
blackjack_payout: 1.5

# Simulation variables
budget: 1000000
bet_multiplier: 1
simulations: 1000
penetration_percentage: 0.25

# Card counting values
1:  -1
2:   1
3:   1
4:   1
5:   1
6:   1
7:   0
8:   0
9:   0
10: -1
11: -1
