# Blackjack Rules
decks: 6
minimum_bet: 10
maximum_bet: 500
blackjack_payout: 1.5

# Simulation variables
budget: 1000000
bet_multiplier: 1
simulations: 10
penetration_percentage: 0.25
output: Y

# Card counting values
# Standardized Revere-RAPC
1:  -1.36
2:   0.68
3:   1.02
4:   1.02
5:   1.36
6:   1.02
7:   0.68
8:   0
9:   -0.34
10: -1.02
11: -1.36